name: Deploy Frontend
on:
  workflow_dispatch:
  push:
    branches:
      - master
# master 에 푸시할 때 마다

# build 잡을 수행.
# ubuntu-latest를 기반으로
# steps에 해당하는 작업을 차례대로 수행

# 기존 비밀번호에 $이 포함되어 로그인이 제대로 수행되지 않음
# -> docker login 수행시 access 토큰을 이용하도록 설정하여 $ 사용을 방지

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t blaxsior/test -f Dockerfile.dev .
      - run: docker run -e CI=true blaxsior/test npm run test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          use_existing_version_if_available: true
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-test
          environment_name: Dockertest-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-608734287208
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
